app = "snaptosize-app"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "7860"
  GRADIO_SERVER_NAME = "0.0.0.0"
  GRADIO_SERVER_PORT = "7860"

[http_service]
  processes = ["app"]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[processes]
  app = "python app.py"
